[package]
name = "amongus-stats-exporter"
version = "0.1.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
byteorder = "1"
clipboard-win = "4"
directories = "3"
error-code = "2"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]
